FROM rocker/tidyverse:3.6.2

RUN Rscript -e "install.packages('fuzzyjoin')"

COPY baseline_demo/cadsr_pv_expanded.feather /user_data/cadsr_pv_expanded.feather
COPY bin/run_baseline.R /run_baseline.R
COPY R/baseline_annotator.R /R/baseline_annotator.R

ENTRYPOINT [ "Rscript", "/run_baseline.R" ]
